### ISSUE TITLE
项目如何正确启动？

### ISSUE THREAD

**Issue by Qiuzero** [zhaodeezhu/drawio-node#2]
drawio-node 项目如何正确启动？

**Comment by Qiuzero** [comment]
![image](https://user-images.githubusercontent.com/59104067/190095964-d02ac0b7-ed53-469e-acde-6dedc967305a.png)

**Comment by zhaodeezhu** [comment]
本地测试环境启动需要执行：npm run dev

如果要部署到生产启动，需要先进行打包一下 npm run server:build
然后再执行：npm run load 启动

今晚我把READMME补充一下，详细说明下启动方式，给您带来了困扰非常抱歉，如果再遇到其他问题，欢迎再次联系

**Comment by Qiuzero** [comment]
> 对 但是报错 

![image](https://user-images.githubusercontent.com/59104067/190101291-e457d1e1-6c37-4622-95a1-30c778847739.png)

**Comment by zhaodeezhu** [comment]
node10.x以上都可以。尝试下将node_modules和package-lock.json都删除，重新执行npm i安装下依赖试试

**Comment by Qiuzero** [comment]
> node10.x以上都可以。尝试下将node_modules和package-lock.json都删除，重新执行npm i安装下依赖试试
试了  同样的错误 项目是完整的吧？

**Comment by zhaodeezhu** [comment]
项目是完整的，我服务器上部署的就是这份。请问是windows电脑，还是mac电脑

**Comment by zhaodeezhu** [comment]
检查下npm的版本，是6.x还是7.x

**Comment by zhaodeezhu** [comment]
如果还不行，请提供下你的环境信息，我去复刻下你的操作环境
操作系统：
NodeJS版本：
npm版本：
typescript版本：

**Comment by Qiuzero** [comment]
> 如果还不行，请提供下你的环境信息，我去复刻下你的操作环境 操作系统： NodeJS版本： npm版本： typescript版本：



![image](https://user-images.githubusercontent.com/59104067/190122449-1893a654-dacc-41f2-a7d2-18a1289d52b8.png)
还是不行 ，版本信息在图上

**Comment by zhaodeezhu** [comment]
好的，晚上回复您

**Comment by Qiuzero** [comment]
> 好的，晚上回复您


ok  多谢

**Comment by Qiuzero** [comment]
我看drawio目录下有java代码 是否需要配置相关Java环境呢

**Comment by zhaodeezhu** [comment]
> 我看drawio目录下有java代码 是否需要配置相关Java环境呢

不需要，这个部分主要的事情就是将java代码替换成node，存在java，只是不想破坏原本项目的结构，方便再使用的时候查看

**Comment by Qiuzero** [comment]
> > 我看drawio目录下有java代码 是否需要配置相关Java环境呢
> 
> 不需要，这个部分主要的事情就是将java代码替换成node，存在java，只是不想破坏原本项目的结构，方便再使用的时候查看


ok

**Comment by zhaodeezhu** [comment]
用了相同的环境，暂时还是无法复现您的报错，在网上也只是查到了些零散的信息，都说是因为安装依赖的时候中途出现紊乱引起的。现在您可以尝试做如下尝试
看看 https://github.com/zhaodeezhu/xioo-docs 这个项目是否可以启动，这个两个项目node服务使用的是同一个框架。
如果上面的项目可以启动，就能印证网上的说法
那么请在此项目中操作
第一：删除node_modules
第二：删除package-lock.json
第三：执行 npm cache clean --force
第四：重新安装依赖，执行 npm i
或者将node版本升级到14.x以上再重复以上操作
如果还是不行，可以将整个项目打包发送到zhaodeemax@gmail.com，我看下你真实的依赖树是什么样的，方便定位问题

**Comment by Qiuzero** [comment]
> 用了相同的环境，暂时还是无法复现您的报错，在网上也只是查到了些零散的信息，都说是因为安装依赖的时候中途出现紊乱引起的。现在您可以尝试做如下尝试 看看 https://github.com/zhaodeezhu/xioo-docs 这个项目是否可以启动，这个两个项目node服务使用的是同一个框架。 如果上面的项目可以启动，就能印证网上的说法 那么请在此项目中操作 第一：删除node_modules 第二：删除package-lock.json 第三：执行 npm cache clean --force 第四：重新安装依赖，执行 npm i 或者将node版本升级到14.x以上再重复以上操作 如果还是不行，可以将整个项目打包发送到[zhaodeemax@gmail.com](mailto:zhaodeemax@gmail.com)，我看下你真实的依赖树是什么样的，方便定位问题



你好，多谢了，xioo-docs是正常的，并且我成功移植到了我的项目当中，xioo-node，按照你说的清了缓存之后，再次执行npm i发现确实有报错，
![image](https://user-images.githubusercontent.com/59104067/190300834-403f60e7-46d5-4760-932e-d3fb8b01f284.png)

项目需要python环境吗？

**Comment by zhaodeezhu** [comment]
我新推了一个版本，升级了xioo，去除了些不必要的依赖，您可以重新pull一下，再安装应该就不需要python了，需要python的原因是低版本的xioo和pg数据库的连接耦合在一起了，所以要有基础python环境。现在进行了拆包动作，已经不需要了，重新pull一下再执行npm i

**Comment by Qiuzero** [comment]
> 我的，升级了一些新版本的xi和一个新版本，你可以升级一下，再安装就不用python了，需要python的原因是低版本的xioopg数据库的连接应该在哪里一起了，所以有了基础python环境。现在进行了拆包动作，已经没有了，重新拉一下再执行npm i


你好，我尝试过配置python环境，也尝试了你说的pull了最新的代码。启动时还是会报错，可能跟我本地开发环境有关，我让同事尝试一下试试。
![image](https://user-images.githubusercontent.com/59104067/190310782-ff6bad1b-bb9c-48ae-801a-c61ef68d17fd.png)

**Comment by zhaodeezhu** [comment]
我去看了你报错的地方，可能是koaroutwr注册的时候有问题，我又删除了部分代码，你重新pull再尝试下

**Comment by Qiuzero** [comment]
> 我去看了你报错的地方，可能是koaroutwr注册的时候有问题，我又删除了部分代码，你重新pull再尝试下

非常感谢 终于可以了

**Comment by zhaodeezhu** [comment]
> > 我去看了你报错的地方，可能是koaroutwr注册的时候有问题，我又删除了部分代码，你重新pull再尝试下
> 
> 
> 
> 非常感谢 终于可以了

好的 主要原因是因为在win上路由路径处理和mac上存在不同，所以导致了启动错误，现在已经修复。给您带了困扰非常抱歉。感谢您的支持，后续有问题可以随时联系我
